name: ror-dev
services:
  ror:
    container_name: ror-dev
    image: ${DOCKER_IMAGE}-dev
    build:
      context: .
      dockerfile: docker/ror/ror.dev.Dockerfile
    env_file: .env
    environment:
      - BASE_PATH=/app
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app
